import { Router, type IRouter } from "express";
import healthRouter from "./health";
import collectionRouter from "./collection";
import checkoutRouter from "./checkout";
import usersRouter from "./users";
import ordersRouter from "./orders";
import wishlistsRouter from "./wishlists";
import addressesRouter from "./addresses";
import storageRouter from "./storage";
import adminCollectionRouter from "./admin-collection";
import shippingRouter from "./shipping";
import couponsRouter from "./coupons";
import reviewsRouter from "./reviews";
import loyaltyRouter from "./loyalty";
import referralsRouter from "./referrals";
import appointmentsRouter from "./appointments";
import backInStockRouter from "./back-in-stock";
import newsletterRouter from "./newsletter";
import returnsRouter from "./returns";
import invoiceRouter from "./invoice";
import seoRouter from "./seo";
import adminExportsRouter from "./admin-exports";
import adminAnalyticsRouter from "./admin-analytics";
import adminCustomersRouter from "./admin-customers";
import adminBannersRouter from "./admin-banners";
import adminCodRouter from "./admin-cod";
import adminRefundsRouter from "./admin-refunds";
import adminInventoryRouter from "./admin-inventory";
import adminAbandonedRouter from "./admin-abandoned";
import adminNewsletterRouter from "./admin-newsletter";
import adminPincodesRouter from "./admin-pincodes";
import adminStaffRouter from "./admin-staff";
import adminGstr1Router from "./admin-gstr1";
import adminAuditRouter from "./admin-audit";

const router: IRouter = Router();

router.use(healthRouter);
router.use(collectionRouter);
router.use(checkoutRouter);
router.use(usersRouter);
router.use(ordersRouter);
router.use(wishlistsRouter);
router.use(addressesRouter);
router.use(storageRouter);
router.use(adminCollectionRouter);
router.use(shippingRouter);
router.use(couponsRouter);
router.use(reviewsRouter);
router.use(loyaltyRouter);
router.use(referralsRouter);
router.use(appointmentsRouter);
router.use(backInStockRouter);
router.use(newsletterRouter);
router.use(returnsRouter);
router.use(invoiceRouter);
router.use(seoRouter);
router.use(adminExportsRouter);
router.use(adminAnalyticsRouter);
router.use(adminCustomersRouter);
router.use(adminBannersRouter);
router.use(adminCodRouter);
router.use(adminRefundsRouter);
router.use(adminInventoryRouter);
router.use(adminAbandonedRouter);
router.use(adminNewsletterRouter);
router.use(adminPincodesRouter);
router.use(adminStaffRouter);
router.use(adminGstr1Router);
router.use(adminAuditRouter);

export default router;
